package alpaca.dto

case class Account(id: String,
                   status: String,
                   currency: String,
                   buying_power: String,
                   cash: String,
                   portfolio_value: String,
                   pattern_day_trader: Boolean,
                   trading_blocked: Boolean,
                   transfers_blocked: Boolean,
                   account_blocked: Boolean,
                   created_at: String,
                   trade_suspended_by_user: Boolean,
                   shorting_enabled: Boolean,
                   multiplier: String,
                   long_market_value: String,
                   short_market_value: String,
                   equity: String,
                   last_equity: String,
                   initial_margin: String,
                   maintenance_margin: String,
                   daytrade_count: Int,
                   sma: String)
